### ISSUE TITLE
ks secret add with changed environments

### ISSUE THREAD

**Issue by godjirax** [wearedevx/keystone#121]
I want to add a secret.
Prompt ask me if i want to override : yes i do.
I set my new values, and after that ks tells me "Environments have changed", and i loose my modification.
Maybe keystone can show error before set new secret values ?
<img width="529" alt="image" src="https://user-images.githubusercontent.com/10376225/144576232-d23a1d80-66c0-4624-b2d5-5a01104fe436.png">

**Comment by gaelph** [comment]
This might be an occasion to extend the --debug flag is currently only used by ci commands

**Comment by gaelph** [comment]
Oh now I get it… Still a good opportunity though
