### ISSUE TITLE
Hook for running a script after sync

### ISSUE THREAD

**Issue by devx-opensource** [wearedevx/keystone#123]
It would be nice to have a way for running a script after each sync.

I could use it to backup the secrets by using the `ks export` command to an external provider (a dropbox folder in my case).

The hook should be run for any keystone projects and give me some informations about the project who triggered it:
* project absolute path
* project name

The CLI could have a `hook` command to register or remove hooks:

```bash
$ ks hook add path/to/script.sh

On which hook would you like to run this script?
* afterSyncAll (run for all keystone projects)
* afterSync (run only for this project)

Script saved in your config folder: ~/User/Library/...
If you want to edit or overwrite your script, run the command again.
```

Only one script can be attached to a hook in order to keeps things simple.

**Comment by gaelph** [comment]
sync = fetch and/or send messages
