### ISSUE TITLE
Can't remove secret properly

### ISSUE THREAD

**Issue by devx-opensource** [wearedevx/keystone#126]
When I remove a secret, it's still listed as available while being removed from the keystone.yaml file.

**How to reproduce:**

1. `ks secret add MY_SECRET`
2. `ks secret rm MY_SECRET`--> OK
3. `ks secret` --> KO, listed as available

**Comment by gaelph** [comment]
It is an expected behavior.
Indeed completely removing the secret would also remove it for other users, but they might still need the secret on their own working branch.

I believe there is a `--purge` flag to ensure the secret is removed in the cache (and therefore for other users) as well.

**Comment by devx-opensource** [comment]
It works as stated with the flag `--purge`:

`ks secret rm --purge MY_SECRET`
