### ISSUE TITLE
ks fetch

### ISSUE THREAD

**Issue by godjirax** [wearedevx/keystone#32]
## Get remote modifications:
```
$ ks fetch
```

sync .keystone folder
- send current env hash 
  - 204 No content (no message, and user sens last hash 🐱 ) 
  - 200 Env hash / last message for me
    - if 200 and no message, ask someone to forge hash message for me.

**Comment by gaelph** [comment]
On fetch, local project files are not overwritten (only those in the `.keystone` directory are).
Those local files will be overwritten on `ks source --force`. 
`ks source` should display a warning when a newer version is in cache
