### ISSUE TITLE
ks rm / ks purge

### ISSUE THREAD

**Issue by LAbigael** [wearedevx/keystone#42]
rm should not remove secret from the cache, just in keystone.yml
purge should remove secret from cache

**Comment by gaelph** [comment]
Closed by commit [5c6785b](https://github.com/wearedevx/keystone/commit/5c6785b71e5033f327e5f0c9c65ff809973058f8)

`ks secret rm` and `ks file rm` only remove secrets and files from `keystone.yml`.
`ks secret rm --purge` or `ks secret rm -p`, and `ks file rm --purge` or `ks file rm -p` also removes values from the cache of all environments and sends updated environments to all project members.
