### ISSUE TITLE
Role Paywall

### ISSUE THREAD

**Issue by gaelph** [wearedevx/keystone#80]
How to implement the roles paywall

One option is introduce the notion or Organization, such that:
- an organization can be free or paid;
- projects belong to an organization;
- « seats » are the number of unique members of all projects of an organization;

If payment is past due, roles must not be lost,
but simply deactivates role checks. When the owner starts paying again,
roles should behave exactly as before.

**Comment by LAbigael** [comment]
- [ ] Create a default organisation for user
- [ ] organization command to add new
- [ ] Can choose orga when init project (between orga of user's projects)
